export const TANSTACK_QUERY_KEYS = {
  // USER
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_PAGED: "GET_USER_PAGED",

  // TICKET
  CREATE_TICKET: "CREATE_TICKET",
  UPDATE_TICKET: "UPDATE_TICKET",
  DELETE_TICKET: "DELETE_TICKET",
  GET_TICKET_BY_ID: "GET_TICKET_BY_ID",
  GET_TICKET_PAGED: "GET_TICKET_PAGED",
  GET_TICKET_PAGED_WITH_SCOPE: "GET_TICKET_PAGED_WITH_SCOPE",
  GET_TICKET_PAGED_LAST_SEVEN_DAYS: "GET_TICKET_PAGED_LAST_SEVEN_DAYS",
  GET_TICKET_STATUS_COUNT: "GET_TICKET_STATUS_COUNT",

  // NOTIFICATION
  GET_UNREAD_NOTIFICATION_COUNT: "GET_UNREAD_NOTIFICATION_COUNT",
  GET_NOTIFICATION_PAGED: "GET_NOTIFICATION_PAGED",
} as const;

export type TanstackQueryKey = (typeof TANSTACK_QUERY_KEYS)[keyof typeof TANSTACK_QUERY_KEYS];
